Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\DELL\anaconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from modulos import circulo
r=float(input("digite o raio"))
print(circulo.Pi)
print(circulo.area(r))
print(circulo.comprimento_circunferencia(r))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[4], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmodulos[39;00m [38;5;28;01mimport[39;00m circulo
[0;32m      2[0m r[38;5;241m=[39m[38;5;28mfloat[39m([38;5;28minput[39m([38;5;124m"[39m[38;5;124mdigite o raio[39m[38;5;124m"[39m))
[0;32m      3[0m [38;5;28mprint[39m(circulo[38;5;241m.[39mPi)

[1;31mImportError[0m: cannot import name 'circulo' from 'modulos' (unknown location)

